/**
 * Pascal Language Definition for Monaco Editor
 * Supports Turbo Pascal dialect with proper syntax highlighting
 */

import type * as Monaco from 'monaco-editor';

/**
 * Turbo Pascal keywords
 */
const KEYWORDS = [
    // Program structure
    'program',
    'begin',
    'end',
    'var',
    'const',
    'type',
    'label',
    'uses',
    'unit',
    'interface',
    'implementation',
    'initialization',
    'finalization',
    'exports',

    // Control flow
    'if',
    'then',
    'else',
    'while',
    'do',
    'for',
    'to',
    'downto',
    'repeat',
    'until',
    'case',
    'of',
    'with',
    'goto',

    // Procedures and functions
    'procedure',
    'function',

    // Data types
    'integer',
    'real',
    'boolean',
    'char',
    'string',
    'text',
    'file',
    'record',
    'array',
    'set',
    'object',
    'pointer',

    // Modifiers
    'forward',
    'external',
    'inline',
    'interrupt',
    'absolute',
    'packed',

    // Visibility
    'private',
    'public',
    'protected',
    'published',

    // Other
    'nil',
    'in',
    'is',
    'as',
    'inherited',
    'virtual',
    'override',
    'abstract',
    'constructor',
    'destructor',
    'property',
    'read',
    'write',
    'default',
    'nodefault',
    'index',
    'stored',
    'message',
    'reintroduce',
    'overload',
    'static',
    'dynamic',
    'export',
    'name',
    'far',
    'near',
    'assembler',
    'pascal',
    'cdecl',
    'stdcall',
    'safecall',
    'register',
    'popstack',
    'saveregisters',
    'inline',
    'iocheck',
    'local',
    'nostackframe',
    'oldfpccall',
    'safecall',
    'softfloat',
    'varargs',
    'wpascal',
    'cppdecl',
    'far16',
    'interrupt',
    'noreturn',
    'norecurse',
    'noinline',
    'sysv_abi_default',
    'sysv_abi_exception',
    'ms_abi_default',
    'ms_abi_exception',
    'vectorcall',
    'rtti',
    'managed',
    'delayed',
    'experimental',
    'deprecated',
    'platform',
    'unimplemented',
    'library',
    'cvar',
    'weak',
    'weakexternal',
    'alias',
    'objc',
    'objcprotocol',
    'objccategory',
    'objcclass',
    'objcselector',
    'dispinterface',
    'dispId',
    'helper',
    'type',
    'strict',
    'sealed',
    'abstract',
    'final',
    'specialize',
    'generic',
    'operator',
    'reference',
    'partial',
    'record',
    'packed',
    'array',
    'set',
    'file',
    'class',
    'object',
    'interface',
    'dispinterface',
    'helper',
    'exception',
    'try',
    'except',
    'finally',
    'raise',
    'on',
    'at',
    'resourcestring',
    'threadvar',
    'ansiString',
    'unicodeString',
    'wideString',
    'shortString',
    'longString',
    'ansichar',
    'widechar',
    'unicodedata',
    'variant',
    'olevariant',
    'comp',
    'currency',
    'extended',
    'single',
    'double',
    'bytebool',
    'wordbool',
    'longbool',
    'qwordbool',
    'byte',
    'shortint',
    'smallint',
    'word',
    'longint',
    'longword',
    'int64',
    'qword',
    'dword',
    'cardinal',
    'sizeint',
    'sizeuint',
    'ptruint',
    'ptrint',
    'valreal',
    'valuint',
    'valint',
    'codepointer',
    'procpointr',
    'methodpointer',
    'utf8char',
    'ucs2char',
    'ucs4char',
    'utf8string',
    'ucs2string',
    'ucs4string',
    'rawbytestring',
    'pansichar',
    'pwidechar',
    'punicodechar',
    'pchar',
    'pbyte',
    'pshortint',
    'pword',
    'plongint',
    'plongword',
    'pint64',
    'pqword',
    'pcardinal',
    'psizeint',
    'psizeuint',
    'pptruint',
    'pptrint',
    'pboolean',
    'pboolean8',
    'pboolean16',
    'pboolean32',
    'pboolean64',
    'pbytebool',
    'pwordbool',
    'plongbool',
    'pqwordbool',
    'pextended',
    'pcurrency',
    'pvariant',
    'polevariant',
    'pcomp',
    'psingle',
    'pdouble',
    'pstring',
    'pansistring',
    'pwidestring',
    'punicodestring',
    'pshortstring',
    'prawbytestring',
    'putf8string',
    'pucs2string',
    'pucs4string',
    'textfile',
    'file',
    'fileof',
    'text',
    'typedfile',
    'untypedfile',
    'bigendian',
    'littleendian',
    'native',
    'endian',
    'bitpacked',
    'aligned',
    'unaligned',
    'attribute',
    'section',
    'code',
    'data',
    'bss',
    'heap',
    'stack',
    'memory',
    'segment',
    'near',
    'far',
    'huge',
    'nearptr',
    'farptr',
    'seg',
    'ofs',
    'cs',
    'ds',
    'es',
    'fs',
    'gs',
    'ss',
    'bp',
    'sp',
    'ip',
    'ax',
    'bx',
    'cx',
    'dx',
    'si',
    'di',
    'al',
    'bl',
    'cl',
    'dl',
    'ah',
    'bh',
    'ch',
    'dh',
    'eax',
    'ebx',
    'ecx',
    'edx',
    'esi',
    'edi',
    'ebp',
    'esp',
    'eip',
];

/**
 * Built-in functions and procedures
 */
const BUILTINS = [
    // I/O
    'WriteLn',
    'ReadLn',
    'Write',
    'Read',
    'Assign',
    'Close',
    'Reset',
    'Rewrite',
    'Append',
    'AssignFile',
    'CloseFile',
    'BlockRead',
    'BlockWrite',
    'IOResult',
    'Eof',
    'Eoln',
    'SeekEof',
    'SeekEoln',
    'Seek',
    'FilePos',
    'FileSize',
    'Truncate',
    'Flush',
    'Erase',
    'Rename',
    'ChDir',
    'MkDir',
    'RmDir',
    'GetDir',

    // String functions
    'Length',
    'Copy',
    'Pos',
    'Delete',
    'Insert',
    'Concat',
    'UpCase',
    'LowerCase',
    'Trim',
    'TrimLeft',
    'TrimRight',
    'QuotedStr',
    'AnsiUpperCase',
    'AnsiLowerCase',
    'AnsiCompareStr',
    'AnsiCompareText',
    'AnsiStrComp',
    'AnsiStrIComp',
    'AnsiStrLComp',
    'AnsiStrLIComp',
    'AnsiStrLower',
    'AnsiStrUpper',
    'AnsiStrPos',
    'StringReplace',
    'SetLength',
    'Str',
    'Val',

    // Math functions
    'Abs',
    'Sqr',
    'Sqrt',
    'Sin',
    'Cos',
    'Tan',
    'ArcTan',
    'ArcSin',
    'ArcCos',
    'Exp',
    'Ln',
    'Log10',
    'Log2',
    'LogN',
    'Int',
    'Frac',
    'Round',
    'Trunc',
    'Ceil',
    'Floor',
    'Power',
    'IntPower',
    'Max',
    'Min',
    'Inc',
    'Dec',
    'Pred',
    'Succ',
    'Odd',
    'Even',
    'Sign',
    'Pi',
    'Random',
    'Randomize',
    'RandSeed',

    // Conversion functions
    'Chr',
    'Ord',
    'IntToStr',
    'StrToInt',
    'StrToIntDef',
    'FloatToStr',
    'StrToFloat',
    'StrToFloatDef',
    'BoolToStr',
    'StrToBool',
    'StrToBoolDef',
    'DateToStr',
    'TimeToStr',
    'DateTimeToStr',
    'StrToDate',
    'StrToTime',
    'StrToDateTime',
    'Format',
    'FormatFloat',
    'FormatDateTime',
    'FloatToDateTime',
    'DateTimeToFloat',
    'VarToDateTime',
    'DateTimeToTimeStamp',
    'TimeStampToDateTime',
    'MsecsToTimeStamp',
    'TimeStampToMSecs',

    // Date/Time functions
    'Date',
    'Time',
    'Now',
    'DateTimeToStr',
    'StrToDateTime',
    'DayOfWeek',
    'DayOf',
    'MonthOf',
    'YearOf',
    'HourOf',
    'MinuteOf',
    'SecondOf',
    'MilliSecondOf',
    'DaysInMonth',
    'DaysInYear',
    'IsLeapYear',
    'EncodeDate',
    'EncodeTime',
    'DecodeDate',
    'DecodeTime',
    'IncMonth',
    'IncYear',
    'IncDay',
    'IncHour',
    'IncMinute',
    'IncSecond',
    'IncMilliSecond',

    // Memory functions
    'New',
    'Dispose',
    'GetMem',
    'FreeMem',
    'ReAllocMem',
    'FillChar',
    'Move',
    'GetMemoryManager',
    'SetMemoryManager',
    'IsMemoryManagerSet',
    'AllocMem',
    'MemSize',
    'HeapSize',
    'MaxAvail',
    'MemAvail',

    // Dynamic array functions
    'SetLength',
    'Length',
    'High',
    'Low',
    'Copy',
    'Delete',
    'Insert',
    'Concat',
    'Slice',

    // File handling
    'FileExists',
    'DirectoryExists',
    'ForceDirectories',
    'CreateDir',
    'RemoveDir',
    'DeleteFile',
    'RenameFile',
    'ChangeFileExt',
    'ExtractFileExt',
    'ExtractFileName',
    'ExtractFilePath',
    'ExtractFileDir',
    'ExtractFileDrive',
    'ExpandFileName',
    'ExpandUNCFileName',
    'GetCurrentDir',
    'SetCurrentDir',
    'FindFirst',
    'FindNext',
    'FindClose',
    'FileGetAttr',
    'FileSetAttr',
    'FileGetDate',
    'FileSetDate',
    'FileAge',
    'FileSize',

    // System functions
    'Exit',
    'Halt',
    'RunError',
    'Abort',
    'Break',
    'Continue',
    'Assert',
    'ParamCount',
    'ParamStr',
    'GetEnvironmentVariable',
    'GetEnvironmentStrings',
    'Sleep',
    'GetTickCount',
    'TickCount',
    'Beep',

    // Type checking
    'Assigned',
    'TypeOf',
    'TypeInfo',
    'Is',
    'As',
    'InheritsFrom',
    'InstanceSize',
    'ClassParent',
    'ClassName',
    'ClassNameIs',
    'ClassInfo',

    // Exception handling
    'Raise',
    'ExceptObject',
    'ExceptAddr',
    'ExceptionErrorMessage',
    'ShowException',
    'Abort',

    // Pointer functions
    'Addr',
    'Ptr',
    'Seg',
    'Ofs',
    'CSeg',
    'DSeg',
    'PtrToInt',
    'IntToPtr',

    // Other
    'SizeOf',
    'BitSizeOf',
    'AlignOf',
    'TypeInfo',
    'GetTypeKind',
    'GetTypeData',
    'GetEnumName',
    'GetEnumValue',
    'GetPropInfo',
    'SetPropValue',
    'GetPropValue',
    'IsPublishedProp',
    'IsStoredProp',
    'MethodAddress',
    'MethodName',
    'RegisterClass',
    'UnRegisterClass',
    'FindClass',
    'FindGlobalComponent',
    'InitInheritedComponent',
    'WriteComponent',
    'ReadComponent',
    'ObjectBinaryToText',
    'ObjectTextToBinary',
    'ObjectResourceToText',
    'ObjectTextToResource',
    'TestStreamFormat',
    'LineStart',
    'GetUnicodeStr',
    'SetUnicodeStr',
    'GetAnsiStr',
    'SetAnsiStr',
    'GetWideStr',
    'SetWideStr',
    'UniqueString',
    'UniqueAnsiString',
    'UniqueUnicodeString',
    'UniqueWideString',
    'AnsiToUtf8',
    'Utf8ToAnsi',
    'UnicodeToUtf8',
    'Utf8ToUnicode',
    'WideCharToUtf8',
    'Utf8ToWideChar',
    'UnicodeStringToUtf8',
    'Utf8ToUnicodeString',
    'Utf8Encode',
    'Utf8Decode',
    'Utf8ToAnsi',
    'AnsiToUtf8',
    'IsDelimiter',
    'LastDelimiter',
    'StringOfChar',
    'WrapText',
    'BufToStr',
    'StrToBuf',
    'HexToBin',
    'BinToHex',
    'StrToHex',
    'HexToStr',
    'DecodeDateFully',
    'DecodeDateDay',
    'DecodeDateWeek',
    'DecodeDateMonthWeek',
    'DecodeDayOfWeekInMonth',
    'EncodeDateMonthWeek',
    'EncodeDateDay',
    'EncodeDateWeek',
    'EncodeDayOfWeekInMonth',
    'TryEncodeDate',
    'TryEncodeTime',
    'TryEncodeDateTime',
    'TryStrToDate',
    'TryStrToTime',
    'TryStrToDateTime',
    'TryStrToFloat',
    'TryStrToInt',
    'TryStrToInt64',
    'TryStrToBool',
    'TryStrToCurr',
    'StrToCurr',
    'CurrToStr',
    'StrToCurrDef',
    'FormatCurr',
    'FloatToCurr',
    'CurrToFloat',
    'VarToCurr',
    'VarToDateTime',
    'VarToBool',
    'VarToInt',
    'VarToStr',
    'VarToStrDef',
    'VarToWideStr',
    'VarToWideStrDef',
    'VarToSQLTimeStamp',
    'VarToSQLTimeStampDef',
    'VarFromDateTime',
    'VarFromSQLTimeStamp',
    'VarIsArray',
    'VarIsEmpty',
    'VarIsNull',
    'VarIsClear',
    'VarIsType',
    'VarIsCustom',
    'VarIsError',
    'VarIsStr',
    'VarIsBool',
    'VarIsFloat',
    'VarIsOrdinal',
    'VarIsNumeric',
    'VarIsDateTime',
    'VarIsSQLTimeStamp',
    'VarType',
    'VarTypeAsText',
    'VarAsType',
    'VarAsError',
    'VarArrayCreate',
    'VarArrayOf',
    'VarArrayCreateSimple',
    'VarArrayDimCount',
    'VarArrayLowBound',
    'VarArrayHighBound',
    'VarArrayLock',
    'VarArrayUnlock',
    'VarArrayRef',
    'VarArrayGet',
    'VarArrayPut',
    'VarArrayRedim',
    'VarArrayFromStrings',
    'VarArrayToStrings',
    'VarCast',
    'VarClear',
    'VarCopy',
    'VarClone',
    'VarIsEmptyParam',
    'VarSupports',
    'VarCompareValue',
    'VarSameValue',
    'VarRangeCheck',
    'VarInvalidOp',
    'VarOverflowError',
    'VarInvalidCast',
    'VarDivZero',
    'VarNull',
    'VarEmpty',
    'VarNullParam',
    'VarUnknown',
    'VarAny',
    'VarStrArg',
    'VarDispatch',
    'VarError',
    'VarBoolean',
    'VarByte',
    'VarWord',
    'VarLongWord',
    'VarInt64',
    'VarQWord',
    'VarShortInt',
    'VarSmallInt',
    'VarInteger',
    'VarSingle',
    'VarDouble',
    'VarCurrency',
    'VarDate',
    'VarOleStr',
    'VarString',
    'VarArray',
    'VarByRef',
    'VarTypeToDataType',
    'DataTypeToVarType',
    'FindVarInstance',
    'GetVariantManager',
    'SetVariantManager',
    'IsVariantManagerSet',
    'DispInvoke',
    'DispCallFunc',
    'DispGetIDsOfNames',
    'DispGetParam',
    'SafeArrayCreate',
    'SafeArrayDestroy',
    'SafeArrayLock',
    'SafeArrayUnlock',
    'SafeArrayGetDim',
    'SafeArrayGetLBound',
    'SafeArrayGetUBound',
    'SafeArrayGetElemSize',
    'SafeArrayGetElemsize',
    'SafeArrayPtrOfIndex',
    'SafeArrayGetElement',
    'SafeArrayPutElement',
    'SafeArrayAccessData',
    'SafeArrayUnaccessData',
    'SafeArrayRedim',
    'SafeArrayCopy',
    'SafeArrayCreateVector',
    'SafeArrayCreateVectorEx',
    'SafeArrayGetVartype',
    'SafeArraySetVartype',
    'SafeArrayGetRecordInfo',
    'SafeArraySetRecordInfo',
    'SafeArrayGetIID',
    'SafeArraySetIID',
    'SafeArrayCopyData',
    'SafeArrayAllocDescriptor',
    'SafeArrayAllocDescriptorEx',
    'SafeArrayAllocData',
    'SafeArrayDestroyDescriptor',
    'SafeArrayDestroyData',
    'SafeArrayCreateEx',
    'SafeArrayGetDimCount',
    'SafeArrayGetLBoundV',
    'SafeArrayGetUBoundV',
    'SafeArrayGetBoundsV',
    'SafeArraySetBoundsV',
    'SafeArrayGetElementV',
    'SafeArrayPutElementV',
    'SafeArrayPtrOfIndexV',
    'SafeArrayCheckElementV',
    'SafeArrayClearElementV',
    'SafeArrayCopyElementV',
    'SafeArrayAddRefElementV',
    'SafeArrayReleaseElementV',
    'SafeArrayGetElementCount',
    'SafeArrayGetElementSize',
    'SafeArrayGetFeatures',
    'SafeArraySetFeatures',
    'SafeArrayGetLocked',
    'SafeArraySetLocked',
    'SafeArrayGetPtr',
    'SafeArraySetPtr',
    'SafeArrayGetPrivateData',
    'SafeArraySetPrivateData',
    'SafeArrayGetCount',
    'SafeArraySetCount',
    'SafeArrayGetItemSize',
    'SafeArraySetItemSize',
    'SafeArrayGetItemPtr',
    'SafeArraySetItemPtr',
    'SafeArrayGetItemPrivateData',
    'SafeArraySetItemPrivateData',
    'SafeArrayGetItemLocked',
    'SafeArraySetItemLocked',
    'SafeArrayGetItemRef',
    'SafeArraySetItemRef',
    'SafeArrayGetItemCopy',
    'SafeArraySetItemCopy',
    'SafeArrayGetItemClear',
    'SafeArraySetItemClear',
    'SafeArrayGetItemAddRef',
    'SafeArraySetItemAddRef',
    'SafeArrayGetItemRelease',
    'SafeArraySetItemRelease',
    'SafeArrayGetItemCompare',
    'SafeArraySetItemCompare',
    'SafeArrayGetItemHash',
    'SafeArraySetItemHash',
    'SafeArrayGetItemAssign',
    'SafeArraySetItemAssign',
    'SafeArrayGetItemDefault',
    'SafeArraySetItemDefault',
    'SafeArrayGetItemName',
    'SafeArraySetItemName',
    'SafeArrayGetItemType',
    'SafeArraySetItemType',
    'SafeArrayGetItemFlags',
    'SafeArraySetItemFlags',
    'SafeArrayGetItemData',
    'SafeArraySetItemData',
    'SafeArrayGetItemExtra',
    'SafeArraySetItemExtra',
    'SafeArrayGetItemExt',
    'SafeArraySetItemExt',
    'SafeArrayGetItemExtData',
    'SafeArraySetItemExtData',
    'SafeArrayGetItemExtSize',
    'SafeArraySetItemExtSize',
    'SafeArrayGetItemExtFlags',
    'SafeArraySetItemExtFlags',
    'SafeArrayGetItemExtName',
    'SafeArraySetItemExtName',
    'SafeArrayGetItemExtType',
    'SafeArraySetItemExtType',
    'SafeArrayGetItemExtDefault',
    'SafeArraySetItemExtDefault',
    'SafeArrayGetItemExtCompare',
    'SafeArraySetItemExtCompare',
    'SafeArrayGetItemExtHash',
    'SafeArraySetItemExtHash',
    'SafeArrayGetItemExtAssign',
    'SafeArraySetItemExtAssign',
    'SafeArrayGetItemExtClear',
    'SafeArraySetItemExtClear',
    'SafeArrayGetItemExtAddRef',
    'SafeArraySetItemExtAddRef',
    'SafeArrayGetItemExtRelease',
    'SafeArraySetItemExtRelease',
    'SafeArrayGetItemExtCopy',
    'SafeArraySetItemExtCopy',
    'SafeArrayGetItemExtRef',
    'SafeArraySetItemExtRef',
    'SafeArrayGetItemExtLocked',
    'SafeArraySetItemExtLocked',
    'SafeArrayGetItemExtPrivateData',
    'SafeArraySetItemExtPrivateData',
    'SafeArrayGetItemExtCount',
    'SafeArraySetItemExtCount',
    'SafeArrayGetItemExtItemSize',
    'SafeArraySetItemExtItemSize',
    'SafeArrayGetItemExtItemPtr',
    'SafeArraySetItemExtItemPtr',
    'SafeArrayGetItemExtItemPrivateData',
    'SafeArraySetItemExtItemPrivateData',
    'SafeArrayGetItemExtItemLocked',
    'SafeArraySetItemExtItemLocked',
    'SafeArrayGetItemExtItemRef',
    'SafeArraySetItemExtItemRef',
    'SafeArrayGetItemExtItemCopy',
    'SafeArraySetItemExtItemCopy',
    'SafeArrayGetItemExtItemClear',
    'SafeArraySetItemExtItemClear',
    'SafeArrayGetItemExtItemAddRef',
    'SafeArraySetItemExtItemAddRef',
    'SafeArrayGetItemExtItemRelease',
    'SafeArraySetItemExtItemRelease',
    'SafeArrayGetItemExtItemCompare',
    'SafeArraySetItemExtItemCompare',
    'SafeArrayGetItemExtItemHash',
    'SafeArraySetItemExtItemHash',
    'SafeArrayGetItemExtItemAssign',
    'SafeArraySetItemExtItemAssign',
    'SafeArrayGetItemExtItemDefault',
    'SafeArraySetItemExtItemDefault',
    'SafeArrayGetItemExtItemName',
    'SafeArraySetItemExtItemName',
    'SafeArrayGetItemExtItemType',
    'SafeArraySetItemExtItemType',
    'SafeArrayGetItemExtItemFlags',
    'SafeArraySetItemExtItemFlags',
    'SafeArrayGetItemExtItemData',
    'SafeArraySetItemExtItemData',
    'SafeArrayGetItemExtItemExtra',
    'SafeArraySetItemExtItemExtra',
];

/**
 * Standard constants
 */
const CONSTANTS = [
    'True',
    'False',
    'MaxInt',
    'MaxLongInt',
    'MaxSmallInt',
    'MaxShortInt',
    'MaxByte',
    'MaxWord',
    'MaxCardinal',
    'MaxQWord',
    'MaxInt64',
    'MinInt',
    'MinLongInt',
    'MinSmallInt',
    'MinShortInt',
    'MinInt64',
    'Null',
    'EmptyParam',
    'Unassigned',
];

/**
 * Operators and symbols
 */
const OPERATORS = [
    ':=',
    '=',
    '<>',
    '<',
    '>',
    '<=',
    '>=',
    '+',
    '-',
    '*',
    '/',
    'div',
    'mod',
    'and',
    'or',
    'not',
    'xor',
    'shl',
    'shr',
    '@',
    '^',
];

/**
 * Register Pascal language with Monaco
 */
export function registerPascalLanguage(monaco: typeof Monaco): void {
    // Register the language
    monaco.languages.register({ id: 'pascal' });

    // Set token provider
    monaco.languages.setMonarchTokensProvider('pascal', {
        keywords: KEYWORDS,
        builtins: BUILTINS,
        constants: CONSTANTS,
        operators: OPERATORS,

        // Define symbols
        symbols: /[=><!~?:&|+*/^%]+/,

        // Define tokenizer rules
        tokenizer: {
            root: [
                // Comments
                [/\{[^}]*\}/, 'comment'],
                [/\(\*[\s\S]*?\*\)/, 'comment'],
                [/\/\/.*$/, 'comment'],

                // Strings
                [/'([^']|'')*'/, 'string'],

                // Numbers
                [/\d*\.\d+([eE][-+]?\d+)?/, 'number.float'],
                [/\$[0-9a-fA-F]+/, 'number.hex'],
                [/\d+/, 'number'],

                // Identifiers and keywords
                [
                    /[a-zA-Z_][a-zA-Z0-9_]*/,
                    {
                        cases: {
                            '@keywords': 'keyword',
                            '@builtins': 'type.identifier',
                            '@constants': 'constant',
                            '@default': 'identifier',
                        },
                    },
                ],

                // Operators
                [/@symbols/, {
                    cases: {
                        '@operators': 'operator',
                        '@default': '',
                    },
                }],

                // Delimiters
                [/[;,.:]/, 'delimiter'],
                [/[(){}[\]]/, '@brackets'],

                // Whitespace
                [/\s+/, 'white'],
            ],
        },

        // Auto-closing pairs
        autoClosingPairs: [
            { open: '{', close: '}' },
            { open: '(', close: ')' },
            { open: '[', close: ']' },
            { open: "'", close: "'", notIn: ['string', 'comment'] },
        ],

        // Brackets
        brackets: [
            { open: '{', close: '}', token: 'delimiter.curly' },
            { open: '(', close: ')', token: 'delimiter.parenthesis' },
            { open: '[', close: ']', token: 'delimiter.square' },
        ],

        // Comments
        comments: {
            blockComment: ['{', '}'],
            lineComment: '//',
        },
    });

    // Set language configuration
    monaco.languages.setLanguageConfiguration('pascal', {
        // Comments
        comments: {
            blockComment: ['{', '}'],
            lineComment: '//',
        },

        // Brackets
        brackets: [
            ['{', '}'],
            ['[', ']'],
            ['(', ')'],
        ],

        // Auto-closing pairs
        autoClosingPairs: [
            { open: '{', close: '}' },
            { open: '[', close: ']' },
            { open: '(', close: ')' },
            { open: "'", close: "'", notIn: ['string', 'comment'] },
        ],

        // Surrounding pairs
        surroundingPairs: [
            { open: '{', close: '}' },
            { open: '[', close: ']' },
            { open: '(', close: ')' },
            { open: "'", close: "'" },
        ],

        // Indentation rules
        indentationRules: {
            increaseIndentPattern: /^\s*(begin|case|class|interface|object|record|try|unit|uses|var|type|const|private|public|protected|published|implementation|initialization|finalization)\b/i,
            decreaseIndentPattern: /^\s*(end|until|finally|except)\b/i,
        },

        // Word pattern
        wordPattern: /(-?\d*\.\d\w*)|([^`~!@#%^&*()\-=+[{\]}\\|;:'",.<>/?\s]+)/g,

        // Folding rules
        folding: {
            markers: {
                start: /^\s*\{\$REGION\b/i,
                end: /^\s*\{\$ENDREGION\b/i,
            },
        },
    });

    // Register completion provider
    monaco.languages.registerCompletionItemProvider('pascal', {
        provideCompletionItems: (model, position) => {
            const word = model.getWordUntilPosition(position);
            const range = {
                startLineNumber: position.lineNumber,
                endLineNumber: position.lineNumber,
                startColumn: word.startColumn,
                endColumn: word.endColumn,
            };

            const suggestions: Monaco.languages.CompletionItem[] = [
                // Keywords
                ...KEYWORDS.map((keyword) => ({
                    label: keyword,
                    kind: monaco.languages.CompletionItemKind.Keyword,
                    insertText: keyword,
                    range,
                    detail: 'Keyword',
                })),
                // Built-in functions
                ...BUILTINS.map((builtin) => ({
                    label: builtin,
                    kind: monaco.languages.CompletionItemKind.Function,
                    insertText: builtin,
                    range,
                    detail: 'Built-in function',
                })),
                // Constants
                ...CONSTANTS.map((constant) => ({
                    label: constant,
                    kind: monaco.languages.CompletionItemKind.Constant,
                    insertText: constant,
                    range,
                    detail: 'Constant',
                })),
            ];

            return { suggestions };
        },
    });
}

export { KEYWORDS, BUILTINS, CONSTANTS, OPERATORS };
